title: From Zero to Tech
email: tania@manco.io
description: >- # this means to ignore newlines until "baseurl:"
  A blog about the journey of Tania Manco from zero to tech.
baseurl: "" # the subpath of your site, e.g. /blog
url: "taniamanco.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username: taniamanco

# Build settings
markdown: kramdown
remote_theme: thelehhman/plainwhite-jekyll
theme: plainwhite
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

plainwhite:
  name: Tania Manco
  tagline: Student. Developer
  date_format: "%b %-d, %Y"
  sitemap: true
  disqus_shortname: from-zero-to-tech
  analytics_id: 'UA-147655571-1'
  social_links:
    github: taniamanco
    linkedIn: in/tania-manco-34a249a5

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
